// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV_fr_6PWHbtOr7cikRkKZxUril-XWhmQ',
    appId: '1:83937718960:web:d9c61f838f83926c4ec175',
    messagingSenderId: '83937718960',
    projectId: 'abhinavmis-f82d0',
    authDomain: 'abhinavmis-f82d0.firebaseapp.com',
    storageBucket: 'abhinavmis-f82d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtxNv2kKkm7H076vBYoE_sgf54Aoz3x-I',
    appId: '1:83937718960:android:b311ad4d9d0b6b4b4ec175',
    messagingSenderId: '83937718960',
    projectId: 'abhinavmis-f82d0',
    storageBucket: 'abhinavmis-f82d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5rE5i3U8AK1oyqh7FLEEGTLsz0bNt5Jw',
    appId: '1:83937718960:ios:9f89b7e4bc64e5954ec175',
    messagingSenderId: '83937718960',
    projectId: 'abhinavmis-f82d0',
    storageBucket: 'abhinavmis-f82d0.appspot.com',
    iosClientId: '83937718960-jo68l7fupi6t21t3tul0orrqhbdqj18n.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginGoogle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5rE5i3U8AK1oyqh7FLEEGTLsz0bNt5Jw',
    appId: '1:83937718960:ios:9f89b7e4bc64e5954ec175',
    messagingSenderId: '83937718960',
    projectId: 'abhinavmis-f82d0',
    storageBucket: 'abhinavmis-f82d0.appspot.com',
    iosClientId: '83937718960-jo68l7fupi6t21t3tul0orrqhbdqj18n.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginGoogle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV_fr_6PWHbtOr7cikRkKZxUril-XWhmQ',
    appId: '1:83937718960:web:933c2aedbf29e9b54ec175',
    messagingSenderId: '83937718960',
    projectId: 'abhinavmis-f82d0',
    authDomain: 'abhinavmis-f82d0.firebaseapp.com',
    storageBucket: 'abhinavmis-f82d0.appspot.com',
  );
}
